const Data = [
  {
    id: "14",
    type: "Initiative",
    statutory: "Constitutional",
    signatures: 149360,
    circulationDate: "01/07/2022",
    stage: "onBallot",
    measureNo: "113",
    petitionerOneName: "Andrea Kennedy-Smith",
    petitionerOneAddress: "3243 NE Daffodil Drive",
    petitionerOneCity: "McMinnville, OR 97218",
    petitionerOnePhone: "(503)707-2434",
    petitionerTwoName: "Reed Scott-Schwalbach",
    petitionerTwoAddress: "1049 SE 80th Avenue",
    petitionerTwoCity: "Portland, OR 97215",
    petitionerTwoPhone: "(503)473-9414",
    petitionerThreeName: "",
    petitionerThreeAddress: "",
    petitionerThreeCity: "",
    petitionerThreePhone: "",
    subject: "Legislative Accountability 1",
    ballotTitle:
      "Amends Constitution: Legislators with ten unexcused absences from floor sessions disqualified from holding next term of office",
    finalNoteText: "Measure 113",
    finalNoteDate: "07/25/2022",
    image:
      "https://c8.alamy.com/comp/RM9E07/the-state-capital-building-adorned-with-the-oregon-pioneer-with-downtown-salem-in-the-background-RM9E07.jpg",
    status: [
      {
        date: "12/21/2020",
        type: "petition-filed",
        text: "Prospective petition filed. To begin the ballot title drafting, chief petitioners must submit 1,000 sponsorship signatures.",
      },
      {
        date: "5/6/2021",
        type: "sponsors-submitted",
        text: "Sponsorship signatures submitted for verification.",
      },
      {
        date: "5/20/2021",
        type: "sponsors-verified",
        text: "Signature verification of sponsorship signatures completed. Petition contains 1,311 signatures.",
      },
      {
        date: "1/7/2022",
        type: "paid-circulation",
        text: "Approved to circulate on yellow paper stock for any petition sheet that will be circulated by paid circulators.",
      },
      {
        date: "2/18/2022",
        type: "volunteer-circulation",
        text: "Approved to circulate on white paper stock for any petition sheet that will be circulated by volunteer circulators.",
      },
      {
        date: "2/22/2022",
        type: "monthly-submission",
        text: "Chief petitioners submitted 4,515 signatures gathered during the previous month by all individuals paid to circulate.",
      },
      {
        date: "3/24/2022",
        type: "monthly-submission",
        text: "Chief petitioners submitted 19,692 signatures gathered during the previous month by all individuals paid to circulate for the total of 24,207.",
      },
      {
        date: "4/13/2022",
        type: "monthly-submission",
        text: "Chief petitioners submitted 42,887 signatures gathered during the previous month by all individuals paid to circulate for the total of 67,094.",
      },
      {
        date: "5/23/2022",
        type: "monthly-submission",
        text: "Chief petitioners submitted 59,013 signatures gathered during the previous month by all individuals paid to circulate for the total of 126,107.",
      },
      {
        date: "5/27/2022",
        type: "signatures-submitted",
        text: "Signatures submitted for verification. 183,942 unverified signatures.",
      },
      {
        date: "7/5/2022",
        type: "petition-qualified",
        text: "Signature verification has been completed. IP 2022-014 contains 155,343 valid signatures, or 84.11% of the 184,680 signatures accepted for verification. Petition has qualified for the November 8, 2022, General Election ballot. The total number of signatures accepted for verification includes sponsorship (1,409) and primary (183,271) signature submittals.",
      },
      {
        date: "7/25/2022",
        type: "measure-created",
        text: "Measure 113",
      },
    ],
  },
  {
    id: "15",
    type: "Initiative",
    statutory: "Constitutional",
    signatures: 149360,
    circulationDate: "01/07/2022",
    stage: "onBallot",
    measureNo: "113",
    petitionerOneName: "Andrea Kennedy-Smith",
    petitionerOneAddress: "3243 NE Daffodil Drive",
    petitionerOneCity: "McMinnville, OR 97218",
    petitionerOnePhone: "(503)707-2434",
    petitionerTwoName: "Reed Scott-Schwalbach",
    petitionerTwoAddress: "1049 SE 80th Avenue",
    petitionerTwoCity: "Portland, OR 97215",
    petitionerTwoPhone: "(503)473-9414",
    petitionerThreeName: "",
    petitionerThreeAddress: "",
    petitionerThreeCity: "",
    petitionerThreePhone: "",
    subject: "Legislative Accountability 1",
    ballotTitle:
      "Amends Constitution: Legislators with ten unexcused absences from floor sessions disqualified from holding next term of office",
    finalNoteText: "Measure 113",
    finalNoteDate: "07/25/2022",
    image:
      "https://c8.alamy.com/comp/RM9E07/the-state-capital-building-adorned-with-the-oregon-pioneer-with-downtown-salem-in-the-background-RM9E07.jpg",
  },
  {
    id: "16",
    type: "Initiative",
    statutory: "Constitutional",
    signatures: 149360,
    circulationDate: "01/07/2022",
    stage: "onBallot",
    measureNo: "113",
    petitionerOneName: "Andrea Kennedy-Smith",
    petitionerOneAddress: "3243 NE Daffodil Drive",
    petitionerOneCity: "McMinnville, OR 97218",
    petitionerOnePhone: "(503)707-2434",
    petitionerTwoName: "Reed Scott-Schwalbach",
    petitionerTwoAddress: "1049 SE 80th Avenue",
    petitionerTwoCity: "Portland, OR 97215",
    petitionerTwoPhone: "(503)473-9414",
    petitionerThreeName: "",
    petitionerThreeAddress: "",
    petitionerThreeCity: "",
    petitionerThreePhone: "",
    subject: "Legislative Accountability 1",
    ballotTitle:
      "Amends Constitution: Legislators with ten unexcused absences from floor sessions disqualified from holding next term of office",
    finalNoteText: "Measure 113",
    finalNoteDate: "07/25/2022",
    image:
      "https://c8.alamy.com/comp/RM9E07/the-state-capital-building-adorned-with-the-oregon-pioneer-with-downtown-salem-in-the-background-RM9E07.jpg",
  },
];

export default Data;
