const Data = [
  {
    id: "14",
    type: "Initiative",
    statutory: "Constitutional",
    signatures: 149360,
    circulationDate: "01/07/2022",
    stage: "onBallot",
    measureNo: "113",
    petitionerOneName: "Andrea Kennedy-Smith",
    petitionerOneAddress: "3243 NE Daffodil Drive",
    petitionerOneCity: "McMinnville, OR 97218",
    petitionerOnePhone: "(503)707-2434",
    petitionerTwoName: "Reed Scott-Schwalbach",
    petitionerTwoAddress: "1049 SE 80th Avenue",
    petitionerTwoCity: "Portland, OR 97215",
    petitionerTwoPhone: "(503)473-9414",
    petitionerThreeName: "",
    petitionerThreeAddress: "",
    petitionerThreeCity: "",
    petitionerThreePhone: "",
    subject: "Legislative Accountability 1",
    ballotTitle:
      "Amends Constitution: Legislators with ten unexcused absences from floor sessions disqualified from holding next term of office",
    finalNoteText: "Measure 113",
    finalNoteDate: "07/25/2022",
    image: "https://c8.alamy.com/comp/RM9E07/the-state-capital-building-adorned-with-the-oregon-pioneer-with-downtown-salem-in-the-background-RM9E07.jpg",
  },
  {
    id: "15",
    type: "Initiative",
    statutory: "Constitutional",
    signatures: 149360,
    circulationDate: "01/07/2022",
    stage: "onBallot",
    measureNo: "113",
    petitionerOneName: "Andrea Kennedy-Smith",
    petitionerOneAddress: "3243 NE Daffodil Drive",
    petitionerOneCity: "McMinnville, OR 97218",
    petitionerOnePhone: "(503)707-2434",
    petitionerTwoName: "Reed Scott-Schwalbach",
    petitionerTwoAddress: "1049 SE 80th Avenue",
    petitionerTwoCity: "Portland, OR 97215",
    petitionerTwoPhone: "(503)473-9414",
    petitionerThreeName: "",
    petitionerThreeAddress: "",
    petitionerThreeCity: "",
    petitionerThreePhone: "",
    subject: "Legislative Accountability 1",
    ballotTitle:
      "Amends Constitution: Legislators with ten unexcused absences from floor sessions disqualified from holding next term of office",
    finalNoteText: "Measure 113",
    finalNoteDate: "07/25/2022",
    image: "https://c8.alamy.com/comp/RM9E07/the-state-capital-building-adorned-with-the-oregon-pioneer-with-downtown-salem-in-the-background-RM9E07.jpg",
  },
  {
    id: "16",
    type: "Initiative",
    statutory: "Constitutional",
    signatures: 149360,
    circulationDate: "01/07/2022",
    stage: "onBallot",
    measureNo: "113",
    petitionerOneName: "Andrea Kennedy-Smith",
    petitionerOneAddress: "3243 NE Daffodil Drive",
    petitionerOneCity: "McMinnville, OR 97218",
    petitionerOnePhone: "(503)707-2434",
    petitionerTwoName: "Reed Scott-Schwalbach",
    petitionerTwoAddress: "1049 SE 80th Avenue",
    petitionerTwoCity: "Portland, OR 97215",
    petitionerTwoPhone: "(503)473-9414",
    petitionerThreeName: "",
    petitionerThreeAddress: "",
    petitionerThreeCity: "",
    petitionerThreePhone: "",
    subject: "Legislative Accountability 1",
    ballotTitle:
      "Amends Constitution: Legislators with ten unexcused absences from floor sessions disqualified from holding next term of office",
    finalNoteText: "Measure 113",
    finalNoteDate: "07/25/2022",
    image: "https://c8.alamy.com/comp/RM9E07/the-state-capital-building-adorned-with-the-oregon-pioneer-with-downtown-salem-in-the-background-RM9E07.jpg",
  },
];

export default Data;
